[package]
name = "bluedar-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = ["canvas", "tokio"] }
rumqttc = { version = "0.24.0", default-features = false }
